apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-factory
  labels:
    app: operator-factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator-factory
  template:
    metadata:
      labels:
        app: operator-factory
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: sm-key
      containers:
        - name: operator-factory
          image: gcr.io/studio-staging-294712/arcadia.operator.factory.stage:latest
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: arcadia-stage
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: arcadia-stage
                  key: OF_API_PORT
            - name: USE_GCP_SM
              valueFrom:
                configMapKeyRef:
                  name: arcadia-stage
                  key: USE_GCP_SM
            - name: API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: arcadia-stage
                  key: OF_API_VERSION
            - name: GCP_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: arcadia-stage
                  key: GCP_PROJECT
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
