apiVersion: v1
kind: Service
metadata:
  labels:
    name: operator-factory
  name: operator-factory-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: operator-factory
  type: NodePort
