export const REDIS_SUBSCRIBER_CLIENT = 'REDIS_SUBSCRIBER_CLIENT';
export const REDIS_PUBLISHER_CLIENT = 'REDIS_PUBLISHER_CLIENT';
export const PLAYER_DIRECT_ROOM_NAME_TEMPLATE = 'player-direct-room-{cid}';
