steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "arcadia.robot.emulator/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/arcadia.robot.emulator.stage:$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/arcadia.robot.emulator.stage:latest",
        "./arcadia.robot.emulator",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/arcadia.robot.emulator.stage"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'arcadia.robot.emulator/deployment/k8s/stage', '--namespace=${_ENV}']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set',
      'image',
      'deployment',
      'robot-emulator',
      'robot-emulator=gcr.io/$PROJECT_ID/arcadia.robot.emulator.stage:$BUILD_ID',
      '--namespace=${_ENV}'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

