steps:
    - name: node:10.15.1
      entrypoint: npm
      dir: 'arcadia.dal'
      args: ['install']
    - name: node:10.15.1
      entrypoint: npm
      dir: 'arcadia.dal'
      args: ['run', 'typeorm:cli', 'migration:run', '\-c AUDIT']
      env:
        - 'DB_SLAVE_PORT=${_DB_PORT}'
        - 'DB_MASTER_PORT=${_DB_PORT}'
        - 'DB_AUDIT_PORT=${_DB_PORT}'
        - 'DB_MASTER_PSW=${_DB_PSW}'
        - 'DB_SLAVE_PSW=${_DB_PSW}'
        - 'DB_AUDIT_PSW=${_DB_PSW}'
        - 'DB_MASTER_NAME=${_DB_NAME}'
        - 'DB_SLAVE_NAME=${_DB_NAME}'
        - 'DB_AUDIT_NAME=${_DB_AUDIT_NAME}'
        - 'DB_MASTER_HOST=${_DB_HOST}'
        - 'DB_SLAVE_HOST=${_DB_HOST}'
        - 'DB_AUDIT_HOST=${_DB_HOST}'
        - 'DB_AUDIT_USER=${_DB_USER}'
        - 'DB_SLAVE_USER=${_DB_USER}'
        - 'DB_MASTER_USER=${_DB_USER}'
