steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "arcadia.game.core.api/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/arcadia.game.core.api.dev:$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/arcadia.game.core.api.dev:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/arcadia.game.core.api.dev"]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh --zone "${_ZONE}" "${_INSTANCE}" --command "
        cd /home/arcadia
        docker stop arcadia_game_core_api_1
        docker-compose pull game_core_api_1
        docker-compose create game_core_api_1
        docker-compose start game_core_api_1
        "
        wait
