export enum ModuleTags {
    ADMINISTRATION = 'administration',
    ALERTS = 'alerts',
    CAMERAS = 'cameras',
    DISPUTES = 'disputes',
    GROUPS = 'groups',
    JACKPOTS = 'jackpots',
    MACHINES = 'machines',
    MAINTENANCE = 'maintenance',
    MONITORING = 'monitoring',
    OPERATORS = 'operators',
    PLAYERS = 'players',
    SESSIONS = 'sessions',
    VOUCHERS = 'vouchers',
    HISTORY = 'history',
    REPORTS = 'reports',
    DASHBOARD = 'dashboard',
}
