apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-core-worker
  labels:
    app: game-core-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-core-worker
  template:
    metadata:
      labels:
        app: game-core-worker
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: sm-key
      containers:
        - name: game-core-worker
          image: gcr.io/studio-staging-294712/arcadia.game.core.worker.stage:latest
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: arcadia-stage
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: arcadia-stage
                  key: GCW_API_PORT
            - name: USE_GCP_SM
              valueFrom:
                configMapKeyRef:
                  name: arcadia-stage
                  key: USE_GCP_SM
            - name: API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: arcadia-stage
                  key: GCW_API_VERSION
            - name: GCP_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: arcadia-stage
                  key: GCP_PROJECT
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
