apiVersion: v1
kind: Service
metadata:
  labels:
    name: game-core-worker
  name: game-core-worker-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: game-core-worker
  type: NodePort
