apiVersion: v1
kind: Service
metadata:
  labels:
    name: backoffice-api
  name: backoffice-api-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: backoffice-api
  type: NodePort
