apiVersion: v1
kind: Service
metadata:
  labels:
    name: game-core-api
  name: game-core-api-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: game-core-api
  type: NodePort
