export const CHIP_DETECTION_VISIBILITY_TIME = 6000;
export const CHIP_WIN_VISIBILITY_TIME = 1000;
export const BET_BEHIND_STATUS_RESET_TIMEOUT = 1000;
export const MACHINE_SEEDING_DETECTION_DELAY = 2000;
