apiVersion: v1
kind: Service
metadata:
  labels:
    name: client-api
  name: client-api-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: client-api
  type: NodePort
