apiVersion: v1
kind: Service
metadata:
  labels:
    name: chip-distributor
  name: chip-distributor-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: chip-distributor
  type: NodePort
