export enum CsrtcPlayerStatusEnum {
    FAILED = 'FAILED',
    NEW = 'NEW',
    NOT_ENOUGH_BANDWIDTH = 'NOT_ENOUGH_BANDWIDTH',
    PAUSED = 'PAUSED',
    PENDING = 'PENDING',
    PLAYBACK_PROBLEM = 'PLAYBACK_PROBLEM',
    PLAYING = 'PLAYING',
    PUBLISHING = 'PUBLISHING',
    RESIZE = 'RESIZE',
    SNAPSHOT_COMPLETE = 'SNAPSHOT_COMPLETE',
    STOPPED = 'STOPPED',
    UNPUBLISHED = 'UNPUBLISHED',
}
