steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "arcadia.backoffice.fe/Dockerfile",
        "--build-arg",
        "API_HOST=${_API_HOST}",
        "-t",
        "gcr.io/$PROJECT_ID/arcadia.backoffice.fe.dev:$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/arcadia.backoffice.fe.dev:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/arcadia.backoffice.fe.dev"]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh --zone "${_ZONE}" "${_INSTANCE}" --command "
        cd /home/arcadia
        docker stop arcadia_backoffice_fe
        docker-compose pull arcadia-backoffice-fe
        docker-compose create arcadia-backoffice-fe
        docker-compose start arcadia-backoffice-fe
        "
        wait
timeout: 900s
