apiVersion: v1
kind: Service
metadata:
  labels:
    name: robot-emulator
  name: robot-emulator-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: robot-emulator
  type: NodePort
