apiVersion: v1
kind: Service
metadata:
  labels:
    name: monitoring-worker
  name: monitoring-worker-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: monitoring-worker
  type: NodePort
