/* eslint-disable max-lines */
export const mockedCameras = [
  {
    id: '111',
    type: 'hikvision',
    ip: '192.168.1.63',
    adminUrl: 'http://192.168.1.63:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location2',
    comments: 'test',
    status: 'online',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '112',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location2',
    comments: 'test',
    status: 'offline',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '113',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'offline',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '114',
    type: 'dahua',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location2',
    comments: 'test',
    status: 'offline',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '115',
    type: 'dahua',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'offline',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '116',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'online',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '117',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'online',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '118',
    type: 'dahua',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'unknown',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '119',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'online',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '120',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'online',
    rtsp: 'S14L',
  },
  {
    id: '121',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'online',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '122',
    type: 'dahua',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'offline',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '123',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'online',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '124',
    type: 'dahua',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'online',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '125',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'online',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '126',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'online',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '127',
    type: 'dahua',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'online',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '128',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'offline',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '129',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.64:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'offline',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '130',
    type: 'hikvision',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.69:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'offline',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '131',
    type: 'hikvision',
    ip: '192.168.1.69',
    adminUrl: 'http://192.168.1.69:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location1',
    comments: 'test',
    status: 'offline',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
  {
    id: '132',
    type: 'dahua',
    ip: '192.168.1.64',
    adminUrl: 'http://192.168.1.69:80/',
    adminUser: 'admin',
    adminPasw: '12345',
    site: 'main site',
    location: 'location2',
    comments: 'test',
    status: 'offline',
    consoleUrl: 'http://google.com/',
    rtsp: 'S14L',
  },
];

export const streamsMocks = [
  {
    cameraID: '111',
    streamID: 'rtsp://admin:Arcadia2020@31.154.132.21:554/Streaming/Channels/101',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '111',
    streamID: 'rtsp://admin:Arcadia2020@31.154.132.21:554/Streaming/Channels/102',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '112',
    streamID: 'rtsp://admin:Arcadia2020@31.154.132.21:554/Streaming/Channels/101',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '112',
    streamID: 'rtsp://admin:Arcadia2020@31.154.132.21:554/Streaming/Channels/102',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '113',
    streamID: '2434',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '114',
    streamID: '2435',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '115',
    streamID: '2436',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '116',
    streamID: '2437',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '117',
    streamID: '2438',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '118',
    streamID: '2439',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '119',
    streamID: '2440',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '120',
    streamID: '2441',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '121',
    streamID: '2442',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '122',
    streamID: '2443',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '123',
    streamID: '2444',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '124',
    streamID: '2445',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '125',
    streamID: '2446',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '126',
    streamID: '2447',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '127',
    streamID: '2448',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '128',
    streamID: '2449',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '129',
    streamID: '2450',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: true,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '130',
    streamID: '2451',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: false,
      isRecorded: false,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '131',
    streamID: '2452',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: true,
      isRecorded: false,
    },
    rtsp: 'S14L',
  },
  {
    cameraID: '132',
    streamID: '2453',
    server: 'wss://webrtc.cleversphere.com:8443',
    hlsUrl: 'https://hls.cleversphere.com/Cluster1/S14H/S14H.m3u8',
    status: {
      isOn: false,
      isRecorded: false,
    },
    rtsp: 'S14L',
  },
];
