module.exports = {
  DEFAULT: 'message',
  // to core
  PLAYER_JOINED: 'userJoined',
  PLAYER_LEFT: 'userLeft',
  BUY_STACKS: 'buy',
  ENABLE_AUTOPLAY: 'enableAutoplay',
  DISABLE_AUTOPLAY: 'disableAutoplay',
  ENABLE_BET_BEHIND: 'enableBetBehind',
  DISABLE_BET_BEHIND: 'disableBetBehind',
  BALANCE: 'balance',
  VOUCHER: 'voucher',
  LIST_BETS: 'listbets',
  LEAVE_QUEUE: 'leaveQueue',
  QUEUE_BALANCE: 'queueBalance',
  CANCEL_STACKS: 'cancelStacks',
  // to robot
  INIT: 'init',
  QUIT: 'quit',
  MOVE_RAIL: 'move',
  STOP_RAIL: 'stopMoving',
  OPEN_FIRE: 'openFire',
  CEASE_FIRE: 'ceaseFire',
  SET_ANGLE: 'setAngle',
  SET_SWING_MODE: 'setSwingMode',
  ARM_SWING: 'armSwing',
  ORIENTATION_CHANGED: 'orientationChanged',
  VIDEO: 'video',
  SETTINGS_UPDATE: 'settingsUpdate',
  NOTIFICATION: 'notification',
  MENU_CLICKED: 'menuClicked',
  MENU_CLOSED: 'menuClosed',
  LOST_FOCUS: 'lostFocus',
  REGAINED_FOCUS: 'regainedFocus',
  READY_FOR_NEXT_ROUND: 'readyForNextRound',
};
