steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "arcadia.client.api/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/arcadia.client.api.stage:$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/arcadia.client.api.stage:latest",
        "./arcadia.client.api",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/arcadia.client.api.stage"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'arcadia.client.api/deployment/k8s/stage', '--namespace=${_ENV}']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set',
      'image',
      'deployment',
      'client-api',
      'client-api=gcr.io/$PROJECT_ID/arcadia.client.api.stage:$BUILD_ID',
      '--namespace=${_ENV}'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

