steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "arcadia.client.socketio.node/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/arcadia.client.socketio.node.dev:$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/arcadia.client.socketio.node.dev:latest",
        "./arcadia.client.socketio.node",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/arcadia.client.socketio.node.dev"]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh --zone "${_ZONE}" "${_INSTANCE}" --command "
        cd /home/arcadia
        docker stop arcadia_client_socketio_node_1
        docker stop arcadia_client_socketio_node_2
        docker stop arcadia_client_socketio_node_3
        docker-compose pull client_socketio_node_1
        docker-compose create client_socketio_node_1
        docker-compose create client_socketio_node_2
        docker-compose create client_socketio_node_3
        docker-compose start client_socketio_node_1
        docker-compose start client_socketio_node_2
        docker-compose start client_socketio_node_3
        "
        wait
