export enum DashboardWidgets {
  ACTIVE_NEW_PLAYERS = 'ACTIVE_NEW_PLAYERS',
  EXISTING_NEW_PLAYERS = 'EXISTING_NEW_PLAYERS',
  ACTIVE_SESSIONS_BREAKDOWN = 'ACTIVE_SESSIONS_BREAKDOWN',
  MACHINES_AVAILABILITY = 'MACHINES_AVAILABILITY',
  MACHINES_STATUS = 'MACHINES_STATUS',
  LATEST_ALERTS = 'LATEST_ALERTS',
  WAIT_TIME = 'WAIT_TIME',
  BETTING_ACTIVITY = 'BETTING_ACTIVITY',
  THIRTY_DAYS_ACTIVE_NEW_PLAYERS = 'THIRTY_DAYS_ACTIVE_NEW_PLAYERS',
  TOP_WINNERS_LOSERS = 'TOP_WINNERS_LOSERS',
}
