export enum PerformanceIndicatorMetric {
  EDGE = 'edge',
  WINS = 'wins',
  ARM_SWINGS = 'armSwings',
  CHIP_PUSHES = 'chipPushes',
  ROUND_DURATION = 'roundDuration',
  SESSION_DURATION = 'sessionDuration',
  ILLEGAL_CHIP_DROPS = 'illegalChipDrops',
  HOLD = 'hold',
  POPULATION = 'population',
  UP_PLAYING_TIME = 'upPlayingTime',
  QUEUE_LENGTH = 'queueLength',
  IDLE_DISCONNECTS = 'idleDisconnects',
  SYSTEM_DISCONNECTS = 'systemDisconnects',
  JACKPOT_WON = 'jackpotWon',
  PHANTOM_VALUE_VARIATION = 'phantomValueVariation',
  CHIP_STAY = 'chipStay',
  HARDWARE_FAULTS = 'hardwareFaults',
  OPERATOR_LATENCY = 'operatorLatency',
}
