export enum RobotMessage {
  CmdError = 'CmdError',
  ParseInternalError = 'ParseInternalError',
  Table = 'Table',
  Engaged = 'Engaged',
  Disengaged = 'Disengaged',
  ChipValidation = 'ChipValidation',
  ChipRemoved = 'ChipRemoved',
  Status = 'Status',
  Coin = 'Coin',
  Position = 'Position',
  ChipDrop = 'ChipDrop',
  CeaseFire = 'CeaseFire',
  Move = 'Move',
  Fire = 'Fire',
  StopMoving = 'StopMoving',
  LostConnection = 'LostConnection',
  Pong = 'pong',
}
