import { IGetSessionsResponseBody, SessionStatus } from '../../src/modules/sessions/types';

export const GET_SESSIONS_RESPONSE_MOCK: IGetSessionsResponseBody = {
  total: 8,
  sessions: [
    {
      status: SessionStatus.viewer,
      id: 111,
      groupName: '998',
      machineId: 111,
      operatorName: 'TLp59R',
      playerCid: '2',
      ip: '123.456.876.003',
      startDate: '31/01/2020, 02:12:12',
      duration: 9,
      rounds: 668,
      totalWinning: 100,
      totalNetCash: 100,
      viewerDuration: 56,
      queueDuration: 45,
      totalBets: 2000,
      totalStacksUsed: 5,
      currency: 'EUR',
      clientVersion: '1.0.12',
      os: 'iOS 10.30.2',
      deviceType: 'Mobile',
      browser: 'Safari, 10.30.2',
      groupDetails: 'JSON',
      operationDetails: 'JSON',
      systemConfigs: 'JSON',
      videoUrl: 'bit.ly/4reijfir85',
      operatorSettings: {},
      groupSettings: {},
      systemSettings: {},
    },
    {
      status: SessionStatus.playing,
      id: 222,
      groupName: '998',
      machineId: 222,
      operatorName: 'TLp59R',
      playerCid: '2',
      ip: '123.456.876.003',
      startDate: '31/01/2020, 02:12:12',
      duration: 9,
      rounds: 668,
      totalWinning: 100,
      totalNetCash: 100,
      viewerDuration: 56,
      queueDuration: 45,
      totalBets: 2000,
      totalStacksUsed: 5,
      currency: 'EUR',
      clientVersion: '1.0.12',
      os: 'iOS 10.30.2',
      deviceType: 'Mobile',
      browser: 'Safari, 10.30.2',
      groupDetails: 'JSON',
      operationDetails: 'JSON',
      systemConfigs: 'JSON',
      videoUrl: 'bit.ly/4reijfir85',
      operatorSettings: {},
      groupSettings: {},
      systemSettings: {},
    },
    {
      status: SessionStatus.queue,
      id: 3333,
      groupName: '998',
      machineId: 3333,
      operatorName: 'TLp59R',
      playerCid: '2',
      ip: '123.456.876.003',
      startDate: '31/01/2020, 02:12:12',
      duration: 9,
      rounds: 668,
      totalWinning: 100,
      totalNetCash: 100,
      viewerDuration: 56,
      queueDuration: 45,
      totalBets: 2000,
      totalStacksUsed: 5,
      currency: 'EUR',
      clientVersion: '1.0.12',
      os: 'iOS 10.30.2',
      deviceType: 'Mobile',
      browser: 'Safari, 10.30.2',
      groupDetails: 'JSON',
      operationDetails: 'JSON',
      systemConfigs: 'JSON',
      videoUrl: 'bit.ly/4reijfir85',
      operatorSettings: {},
      groupSettings: {},
      systemSettings: {},
    },
    {
      status: SessionStatus.terminating,
      id: 444,
      groupName: '998',
      machineId: 444,
      operatorName: 'TLp59R',
      playerCid: '2',
      ip: '123.456.876.003',
      startDate: '31/01/2020, 02:12:12',
      duration: 9,
      rounds: 668,
      totalWinning: 100,
      totalNetCash: 100,
      viewerDuration: 56,
      queueDuration: 45,
      totalBets: 2000,
      totalStacksUsed: 5,
      currency: 'EUR',
      clientVersion: '1.0.12',
      os: 'iOS 10.30.2',
      deviceType: 'Mobile',
      browser: 'Safari, 10.30.2',
      groupDetails: 'JSON',
      operationDetails: 'JSON',
      systemConfigs: 'JSON',
      videoUrl: 'bit.ly/4reijfir85',
      operatorSettings: {},
      groupSettings: {},
      systemSettings: {},
    },
    {
      status: SessionStatus.completed,
      id: 555,
      groupName: '998',
      machineId: 555,
      operatorName: 'TLp59R',
      playerCid: '2',
      ip: '123.456.876.003',
      startDate: '31/01/2020, 02:12:12',
      duration: 9,
      rounds: 668,
      totalWinning: 100,
      totalNetCash: 100,
      viewerDuration: 56,
      queueDuration: 45,
      totalBets: 2000,
      totalStacksUsed: 5,
      currency: 'EUR',
      clientVersion: '1.0.12',
      os: 'iOS 10.30.2',
      deviceType: 'Mobile',
      browser: 'Safari, 10.30.2',
      groupDetails: 'JSON',
      operationDetails: 'JSON',
      systemConfigs: 'JSON',
      videoUrl: 'bit.ly/4reijfir85',
      operatorSettings: {},
      groupSettings: {},
      systemSettings: {},
    },
    {
      status: SessionStatus.terminated,
      id: 6666,
      groupName: '998',
      machineId: 6666,
      operatorName: 'TLp59R',
      playerCid: '2',
      ip: '123.456.876.003',
      startDate: '31/01/2020, 02:12:12',
      duration: 9,
      rounds: 668,
      totalWinning: 100,
      totalNetCash: 100,
      viewerDuration: 56,
      queueDuration: 45,
      totalBets: 2000,
      totalStacksUsed: 5,
      currency: 'EUR',
      clientVersion: '1.0.12',
      os: 'iOS 10.30.2',
      deviceType: 'Mobile',
      browser: 'Safari, 10.30.2',
      groupDetails: 'JSON',
      operationDetails: 'JSON',
      systemConfigs: 'JSON',
      videoUrl: 'bit.ly/4reijfir85',
      operatorSettings: {},
      groupSettings: {},
      systemSettings: {},
    },
    {
      status: SessionStatus.terminated,
      id: 777,
      groupName: '998',
      machineId: 777,
      operatorName: 'TLp59R',
      playerCid: '2',
      ip: '123.456.876.003',
      startDate: '31/01/2020, 02:12:12',
      duration: 9,
      rounds: 668,
      totalWinning: 100,
      totalNetCash: 100,
      viewerDuration: 56,
      queueDuration: 45,
      totalBets: 2000,
      totalStacksUsed: 5,
      currency: 'EUR',
      clientVersion: '1.0.12',
      os: 'iOS 10.30.2',
      deviceType: 'Mobile',
      browser: 'Safari, 10.30.2',
      groupDetails: 'JSON',
      operationDetails: 'JSON',
      systemConfigs: 'JSON',
      videoUrl: 'bit.ly/4reijfir85',
      operatorSettings: {},
      groupSettings: {},
      systemSettings: {},
    },
    {
      status: SessionStatus.viewer,
      id: 888,
      groupName: '998',
      machineId: 888,
      operatorName: 'TLp59R',
      playerCid: '2',
      ip: '123.456.876.003',
      startDate: '31/01/2020, 02:12:12',
      duration: 9,
      rounds: 668,
      totalWinning: 100,
      totalNetCash: 100,
      viewerDuration: 56,
      queueDuration: 45,
      totalBets: 2000,
      totalStacksUsed: 5,
      currency: 'EUR',
      clientVersion: '1.0.12',
      os: 'iOS 10.30.2',
      deviceType: 'Mobile',
      browser: 'Safari, 10.30.2',
      groupDetails: 'JSON',
      operationDetails: 'JSON',
      systemConfigs: 'JSON',
      videoUrl: 'bit.ly/4reijfir85',
      operatorSettings: {},
      groupSettings: {},
      systemSettings: {},
    },
  ],
};
