apiVersion: v1
kind: Service
metadata:
  labels:
    name: voucher-portal
  name: voucher-portal-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voucher-portal
  type: NodePort
