steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
        [
          "build",
          "-f",
          "arcadia.backoffice.api/DockerfileCD",
          "-t",
          "gcr.io/$PROJECT_ID/arcadia.chip.distributor.stage:$BUILD_ID",
          "-t",
          "gcr.io/$PROJECT_ID/arcadia.chip.distributor.stage:latest",
          ".",
        ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/arcadia.chip.distributor.stage"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'arcadia.backoffice.api/deployment/k8s/stage/chip-distributor', '--namespace=${_ENV}']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set',
      'image',
      'deployment',
      'chip-distributor',
      'chip-distributor=gcr.io/$PROJECT_ID/arcadia.chip.distributor.stage:$BUILD_ID',
      '--namespace=${_ENV}'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

